Version=1
# 10849.02734375
WorldMap.CenterX=10849.02734375

# 9413.1533203125
WorldMap.CenterY=9413.1533203125

# 18.0
WorldMap.Zoom=18.0

# true
WorldMap.Isometric=true

# true
WorldMap.ShowSymbolsUI=true

# 19.0
MiniMap.Zoom=19.0

# true
MiniMap.Isometric=true

# true
MiniMap.ShowSymbols=true

# false
MiniMap.StartVisible=false