Version=1
# 10880.8369140625
WorldMap.CenterX=10880.8369140625

# 10069.1806640625
WorldMap.CenterY=10069.1806640625

# 18.0
WorldMap.Zoom=18.0

# true
WorldMap.Isometric=true

# true
WorldMap.ShowSymbolsUI=true

# 19.0
MiniMap.Zoom=19.0

# true
MiniMap.Isometric=true

# true
MiniMap.ShowSymbols=true

# false
MiniMap.StartVisible=false