Version=1
# 10702.3505859375
WorldMap.CenterX=10702.3505859375

# 9542.416015625
WorldMap.CenterY=9542.416015625

# 16.5
WorldMap.Zoom=16.5

# true
WorldMap.Isometric=true

# true
WorldMap.ShowSymbolsUI=true

# 19.0
MiniMap.Zoom=19.0

# true
MiniMap.Isometric=true

# true
MiniMap.ShowSymbols=true

# false
MiniMap.StartVisible=false